### ISSUE TITLE
Multiple dex files define Landroid/support/media/ExifInterface$1;

### ISSUE THREAD

**Issue by Wing-Li** [hpdx/fresco-helper#13]
好想用啊，一直找不到到底是哪里错了。
咦嘘

```
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/media/ExifInterface$1;
Error:com.android.dex.DexException: Multiple dex files define Landroid/support/media/ExifInterface$1;
Error:	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:661)
Error:	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:616)
Error:	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:598)
Error:	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Error:	at com.android.dx.merge.DexMerger.merge(DexMerger.java:198)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:61)
Error:	at com.android.builder.dexing.DexArchiveMergerCallable.call(DexArchiveMergerCallable.java:36)
Error:	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
Error:	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
Error:	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
Error:	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
Error:	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error:Execution failed for task ':app:transformDexArchiveWithDexMergerForSmzdkDebug'.
> com.android.build.api.transform.TransformException: com.android.dex.DexException: Multiple dex files define Landroid/support/media/ExifInterface$1;
```

**Comment by hpdx** [comment]
这个问题与该库没关系，是你项目中方法总数超出了65536限制，添加
`defaultConfig {
 multiDexEnabled true
}
`
