### ISSUE TITLE
java.lang.OutOfMemoryError请教一下这个怎么解决

### ISSUE THREAD

**Issue by zhuoshirong** [hpdx/fresco-helper#14]
java.lang.OutOfMemoryError: Failed to allocate a 3000012 byte allocation with 874992 free bytes and 854KB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:831)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:808)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:775)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java)
	at com.facebook.imagepipeline.memory.BitmapPool.alloc(BitmapPool.java)
	at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java)
	at com.facebook.imagepipeline.platform.ArtDecoder.decodeStaticImageFromStream(ArtDecoder.java)
	at com.facebook.imagepipeline.platform.ArtDecoder.decodeJPEGFromEncodedImage(ArtDecoder.java)
	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decodeJpeg(DefaultImageDecoder.java)
	at com.facebook.imagepipeline.decoder.DefaultImageDecoder$1.decode(DefaultImageDecoder.java)
	at com.facebook.imagepipeline.decoder.DefaultImageDecoder.decode(DefaultImageDecoder.java)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.doDecode(DecodeProducer.java)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder.access$300(DecodeProducer.java)
	at com.facebook.imagepipeline.producers.DecodeProducer$ProgressiveDecoder$1.run(DecodeProducer.java)
	at com.facebook.imagepipeline.producers.JobScheduler.doJob(JobScheduler.java)
	at com.facebook.imagepipeline.producers.JobScheduler.access$000(JobScheduler.java)
	at com.facebook.imagepipeline.producers.JobScheduler$1.run(JobScheduler.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java)
	at java.lang.Thread.run(Thread.java:818)

**Comment by hpdx** [comment]
@zhuoshirong Fresco这个图片库，我从2015年开始，已经在多个公司的多个项目中使用，发生OOM的情况多半是参数配置的问题。建议在使用时指定宽高，或者在xml文件中指定要显示的宽高。实在解决不了，建议在https://github.com/facebook/fresco项目下提Issues，尽量详细描述发生问题的场景。
