### ISSUE TITLE
打包release版本时报UnsatisfiedLinkError异常，debug版本是正常的

### ISSUE THREAD

**Issue by liuhuajian** [hpdx/fresco-helper#2]
如标题所示，使用这个框架主要加载webp动图，两台测试机，系统版本分别为5.0和6.0，打包debug版本的时候都是正常的，不过打包release时，出现异常，希望能解决这个问题，异常如下：

02-14 12:07:42.201 24140-24508/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                   Process: com.smartx.tank, PID: 24140
                                                   java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.smartx.tank-2/lib/arm/libimagepipeline.so"
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                       at java.lang.System.loadLibrary(System.java:1076)
                                                       at com.facebook.d.i.a$a.a(SoLoaderShim.java:32)
                                                       at com.facebook.d.i.a.a(SoLoaderShim.java:56)
                                                       at com.facebook.imagepipeline.nativecode.a.a(ImagePipelineNativeLoader.java:43)
                                                       at com.facebook.imagepipeline.memory.NativeMemoryChunk.<clinit>(NativeMemoryChunk.java:36)
                                                       at com.facebook.imagepipeline.memory.m.i(NativeMemoryChunkPool.java:60)
                                                       at com.facebook.imagepipeline.memory.m.b(NativeMemoryChunkPool.java:22)
                                                       at com.facebook.imagepipeline.memory.a.a(BasePool.java:259)
                                                       at com.facebook.imagepipeline.memory.p.<init>(NativePooledByteBufferOutputStream.java:53)
                                                       at com.facebook.imagepipeline.memory.o.a(NativePooledByteBufferFactory.java:141)
                                                       at com.facebook.imagepipeline.memory.o.b(NativePooledByteBufferFactory.java:26)
                                                       at com.facebook.imagepipeline.l.ad.a(NetworkFetchProducer.java:94)
                                                       at com.facebook.imagepipeline.l.ad.a(NetworkFetchProducer.java:37)
                                                       at com.facebook.imagepipeline.l.ad$1.a(NetworkFetchProducer.java:72)
                                                       at com.facebook.imagepipeline.b.a.b$2.a(OkHttpNetworkFetcher.java:122)
                                                       at c.w$b.b(RealCall.java:133)
                                                       at c.a.e.run(NamedRunnable.java:33)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                       at java.lang.Thread.run(Thread.java:818)
                                                   
                                                   
                                                   [ 02-14 12:07:42.201 24140:24140 I/         ]
                                                   values[0] = 0.08619126

**Comment by hpdx** [comment]
可能是so的问题，你可以在gradle中添加下面的代码试试：
   splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a'
            universalApk false
        }
    }

  其中include 'armeabi-v7a'、  include 'armeabi'，要看你们的项目，一般都是统一只使用一种类型的，要么全是armeabi-v7a，要么...
