### ISSUE TITLE
带动画浏览多张图片闪退

### ISSUE THREAD

**Issue by YancyYu** [hpdx/fresco-helper#22]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.util.SparseArray.get(int)' on a null object reference
        at com.facebook.fresco.helper.photoview.anim.TransitionCompat.startTransition(TransitionCompat.java:42)
        at com.facebook.fresco.helper.photoview.PictureBrowseActivity.onCreate(PictureBrowseActivity.java:68)

**Comment by hpdx** [comment]
@YancyYu 
请把使用部分的代码贴一下，我看看？你试试我提供的demo，若是运行demo崩溃的话，麻烦提供下机型、Android版本号

```
ArrayList<PhotoInfo> photos = null;
PhotoX.with(PhotoWallActivity.this)
             .setLayoutManager(mLayoutManager)
             .setPhotoList(photos)
             .setCurrentPosition(position)
             .enabledAnimation(true)
             .start();
```
